server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates: #gelen ıstegı yakalamamızı saglar
            - Path=/auth/** #** auth dan sonra gelebılecek olan ıstegı belırtır
          filters: # Circuit breaker herhangı bır kesıntı oldugunda buraya yonlendırır.
            - name: CircuitBreaker # eger localhost:9090 cevap vermezse fallbackUri adresine yonlendircek
              args:
                name: auth
                fallbackUri: forward:/fallback/auth # bı sorun oldugunda bu adrese gonderıyor
        - id: product-service
          uri: http://localhost:9091
          predicates:
            - Path=/product/**
          filters: # Circuit breaker herhangı bır kesıntı oldugunda buraya yonlendırır.
            - name: CircuitBreaker # eger localhost:9090 cevap vermezse fallbackUri adresine yonlendircek
              args:
                name: product
                fallbackUri: forward:/fallback/product # bı sorun oldugunda bu adrese gonderıyor
        - id: sales-service
          uri: http://localhost:9092
          predicates:
            - Path=/sales/**
          filters: # Circuit breaker herhangı bır kesıntı oldugunda buraya yonlendırır.
            - name: CircuitBreaker # eger localhost:9090 cevap vermezse fallbackUri adresine yonlendircek
              args:
                name: sales
                fallbackUri: forward:/fallback/sales # bı sorun oldugunda bu adrese gonderıyor
        - id: user-service
          uri: http://localhost:9093
          predicates:
            - Path=/user/**
          filters: # Circuit breaker herhangı bır kesıntı oldugunda buraya yonlendırır.
            - name: CircuitBreaker # eger localhost:9090 cevap vermezse fallbackUri adresine yonlendircek
              args:
                name: user
                fallbackUri: forward:/fallback/user # bı sorun oldugunda bu adrese gonderıyor
      default-filters:
        ## http://localhost/auth/findbyid/1
        # (?<segment>.*) -> auth/findbyid/1 segment bu kısmı yakalıyor
        # /$\{segment} -> http://localhost:9090/auth/findbyid/1  buna cevırıyor. Yanı buna yonlendırıyor
        - RewritePath= /(?<segment>.*), /$\{segment} #path de yakaladıgını buna donustur


