server:
  port: 9093

spring:
  rabbitmq:
    host: localhost
    port: 5672 #amqp portu g覺r覺lmel覺
    username: user
    password: root
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  datasource:
    driver-class-nam: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/Java6MicroTekrarUserDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

user-service:
  redis:
    host: localhost
    port: 6379

authservice:
  bunu-ben-yazd覺m:
    secret-key: ${JAVA6_SECRETKEY}
    issuer: ${JAVA6_ISSUER}
